--------------------------------------------------
-- AUTO-GENERATED FILE
--
-- Generated by:
-- tools/generate_tier_token_data.py
--
-- DO NOT EDIT MANUALLY.
--------------------------------------------------

local AL = AscensionLoot

if not AL
    or not AL.TierTokens
then
    return
end

local TT =
    AL.TierTokens

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "NORMAL",
    "WRIST",
    {
        12508,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "NORMAL",
    "LEGS",
    {
        12569,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "NORMAL",
    "HANDS",
    {
        12559,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "NORMAL",
    "HEAD",
    {
        12505,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "NORMAL",
    "WAIST",
    {
        12568,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "NORMAL",
    "SHOULDERS",
    {
        12506,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "NORMAL",
    "CHEST",
    {
        12507,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "NORMAL",
    "BOOTS",
    {
        12570,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "HEROIC",
    "WRIST",
    {
        312508,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "HEROIC",
    "LEGS",
    {
        312569,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "HEROIC",
    "HANDS",
    {
        312559,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "HEROIC",
    "HEAD",
    {
        312505,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "HEROIC",
    "WAIST",
    {
        312568,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "HEROIC",
    "SHOULDERS",
    {
        312506,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "HEROIC",
    "CHEST",
    {
        312507,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "HEROIC",
    "BOOTS",
    {
        312570,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "MYTHIC",
    "WRIST",
    {
        1312508,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "MYTHIC",
    "LEGS",
    {
        1312569,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "MYTHIC",
    "HANDS",
    {
        1312559,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "MYTHIC",
    "HEAD",
    {
        1312505,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "MYTHIC",
    "WAIST",
    {
        1312568,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "MYTHIC",
    "SHOULDERS",
    {
        1312506,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "MYTHIC",
    "CHEST",
    {
        1312507,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "MYTHIC",
    "BOOTS",
    {
        1312570,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "ASCENDED",
    "WRIST",
    {
        212508,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "ASCENDED",
    "LEGS",
    {
        212569,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "ASCENDED",
    "HANDS",
    {
        212559,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "ASCENDED",
    "HEAD",
    {
        212505,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "ASCENDED",
    "WAIST",
    {
        212568,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "ASCENDED",
    "SHOULDERS",
    {
        212506,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "ASCENDED",
    "CHEST",
    {
        212507,
    }
)

TT:AddRewardsByMeta(
    "T1",
    "Molten Core",
    "ASCENDED",
    "BOOTS",
    {
        212570,
    }
)
